### ISSUE TITLE
Prevent initial value optionally

### ISSUE THREAD

**Issue by itsjustbrian** [unicef-polymer/etools-datepicker#3]
The datepicker defaults to the current date. Which is handy for selection, but not if trying avoid an initial value in the input. Trying to adjust for this outside the element is very difficult because this value is set very late into the element lifecycle, so any adjustments are overwritten, and it becomes indistinguishable from actual input.
I'm thinking there needs to be an optional flag for no initial value (with the catch being the actual datepicker window should still start on the current date, but not output this value to it's properties).

**Comment by nmezzopera** [comment]
Recently Adrian added a no-init attribute. Just drop it in and it will not auto initialize

**Comment by adi130987** [comment]
@fafcrumb ... it seems that I forgot to add this no-init flag in the documentation. I will do it now.

**Comment by adi130987** [comment]
@fafcrumb I documented noInit flag here #4

**Comment by itsjustbrian** [comment]
@lordfuoco @adi130987 thanks guys, working perfectly now. Closing this
